### ISSUE TITLE
Stack creation fails on S3 403 error

### ISSUE THREAD

**Issue by TimBanks** [aws-samples/aws-transcribe-captions-live#4]
Running stack deployment using the console link in the Readme. Get the following permissions error trying to create the stack, resulting in rollback:

```
Your access has been denied by S3, please make sure your request credentials have permission to GetObject for rodeolabz-us-east-2/live-streaming-on-aws/livecaptionsv1cbs/TranscribeStreamingJavaLambda.jar. S3 Error Code: AccessDenied. S3 Error Message: Access Denied (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: 791e0593-1ff5-11e9-92f3-b55ab87d2b9b)
```

**Comment by EddieGoynesAmazon** [comment]
Thanks for pointing this out. I had to add a --acl public-read to make the files reachable. 

But this CloudFormation will not work in Ohio (us-east-2), since AWS MediaPackage is not been made available in that region. This solution uses AWS MediaLive and AWS MediaPackage. This link shows the regions that those two services are supported in.

https://docs.aws.amazon.com/general/latest/gr/rande.html
